# Check out https://docs.codemagic.io/getting-started/building-a-native-android-app/ for more information

workflows:
    android-app:
        name: Quotes Trivia
        environment:
            vars:
                SONAR_TOKEN: "Encrypted(Z0FBQUFBQmZpQmtjU3JxNFJMOHBNMXYzZV9yMkZpb1p0Y2NKQ0pWbjhiNjNRLWhzcndDa2NMRU5teTVtVWlpYlFCTnF6eHVLMlNDaTVVQWxERHJGb2JRX0tZSm5jOUtmQUZ6Q2FVQjlzSW43VGE0WkZYdzVuOHVYSHdkSHdTOE82MlAzVXNoeEVPSm8=)"
                SONAR_PROJECT_KEY: "Encrypted(Z0FBQUFBQmZpQ2FhcUhvRURjV3BCcUl0aUwzMWFNNi1hV2NBVnVWS2o3RjVwbmwwNkktdVZrcERKRGF0RFdWSkJkcnBpT213UVJxcXNfUWpJdGtYWlEyQzVQQ3ZPMTExWlZQemhkbnNyRmljS2wxRURSa01tSDQ9)"
                SONAR_ORG_KEY: "Encrypted(Z0FBQUFBQmZpQ2E2ZUQ3N3NwajdDOUhYYkRXUnN3WW84WEdNeVBYUm1LcjNxLW5NdV9JVWMxbUt5cVc0VHUySWNYeVhIX3pMNGtjVklwTlY0MTBDX1dVX3VQNXBlbVZRRnc9PQ==)"
        scripts:
            - ./gradlew assembleDebug
            - ./gradlew sonarqube 
            -Dsonar.projectKey=$SONAR_PROJECT_KEY
            -Dsonar.organization=$SONAR_ORG_KEY 
            -Dsonar.projectVersion=1.0.0-cm 
            -Dsonar.host.url=https://sonarcloud.io 
            -Dsonar.login=$SONAR_TOKEN
        artifacts:
            - app/build/outputs/**/*.apk
