# Check out https://docs.codemagic.io/getting-started/building-a-native-android-app/ for more information

workflows:
    android-app:
        name: Quotes Trivia
        scripts:
            - ./gradlew assembleDebug
        artifacts:
            - app/build/outputs/**/*.apk